import { connect } from "@/dbConfig/dbConfig";
import Expert from "@/models/expertModel";
import { NextResponse } from "next/server";

connect();

export async function POST() {
	try {
		const mockData = [
			{
				name: "Theodore Jovanni 1",
				badge: "Renewable Energy",
				title: "Senior Urban Planner",
				company: "Dan Company",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-0.jpeg",
			},
			{
				name: "Michael Johnson 2",
				badge: "Renewable Energy",
				title: "Real Estate Development Manager",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Environment & Sustainability",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-1.jpeg",
			},
			{
				name: "Samantha Lee 3",
				badge: "Sustainable Agriculture",
				title: "Property Asset Manager",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-2.jpeg",
			},
			{
				name: "Ethan Dion 4",
				badge: "Engineering",
				title: "Infrastructure Development Lead",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Construction",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-3.jpeg",
			},
			{
				name: "Isaac Rodriguez 5",
				badge: "Sustainability",
				title: "Sustainability Consultant",
				company: "Google",
				yearsOfExperience: "12+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-4.jpeg",
			},
			{
				name: "Wyatt Murphy 6",
				badge: "Engineering",
				title: "Dean Engineer",
				company: "MIT",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-5.jpeg",
			},
			{
				name: "Sophia Patel 7",
				badge: "Circular Economy",
				title: "Project Director - Mega Projects",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-6.jpeg",
			},
			{
				name: "Hussam Raouf 8",
				badge: "Engineering",
				title: "Corporate Strategy Advisor",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-7.png",
			},
			{
				name: "Joseph Cillian 9",
				badge: "Renewable Energy",
				title: "Land Acquisition Expert",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Renewable Energy",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-8.jpeg",
			},
			{
				name: "Theodore Jovanni 10",
				badge: "Renewable Energy",
				title: "Senior Urban Planner",
				company: "Dan Company",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-9.png",
			},
			{
				name: "Michael Johnson 11",
				badge: "Renewable Energy",
				title: "Real Estate Development Manager",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Environment & Sustainability",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-10.png",
			},
			{
				name: "Samantha Lee 12",
				badge: "Sustainable Agriculture",
				title: "Property Asset Manager",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-11.png",
			},
			{
				name: "Ethan Dion 13",
				badge: "Engineering",
				title: "Infrastructure Development Lead",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Construction",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-1.jpeg",
			},
			{
				name: "Isaac Rodriguez 14",
				badge: "Sustainability",
				title: "Sustainability Consultant",
				company: "Google",
				yearsOfExperience: "12+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-2.jpeg",
			},
			{
				name: "Wyatt Murphy 15",
				badge: "Engineering",
				title: "Dean Engineer",
				company: "MIT",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-3.jpeg",
			},
			{
				name: "Sophia Patel 16",
				badge: "Circular Economy",
				title: "Project Director - Mega Projects",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-4.jpeg",
			},
			{
				name: "Hussam Raouf 17",
				badge: "Engineering",
				title: "Corporate Strategy Advisor",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-5.jpeg",
			},
			{
				name: "Joseph Cillian 18",
				badge: "Renewable Energy",
				title: "Land Acquisition Expert",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Renewable Energy",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-6.jpeg",
			},
			{
				name: "Theodore Jovanni 19",
				badge: "Renewable Energy",
				title: "Senior Urban Planner",
				company: "Dan Company",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-7.png",
			},
			{
				name: "Michael Johnson 20",
				badge: "Renewable Energy",
				title: "Real Estate Development Manager",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Environment & Sustainability",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-8.jpeg",
			},
			{
				name: "Samantha Lee 21",
				badge: "Sustainable Agriculture",
				title: "Property Asset Manager",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-9.png",
			},
			{
				name: "Ethan Dion 22",
				badge: "Engineering",
				title: "Infrastructure Development Lead",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Construction",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-10.png",
			},
			{
				name: "Isaac Rodriguez 23",
				badge: "Sustainability",
				title: "Sustainability Consultant",
				company: "Google",
				yearsOfExperience: "12+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-11.png",
			},
			{
				name: "Wyatt Murphy 24",
				badge: "Engineering",
				title: "Dean Engineer",
				company: "MIT",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-0.jpeg",
			},
			{
				name: "Sophia Patel 25",
				badge: "Circular Economy",
				title: "Project Director - Mega Projects",
				company: "ARDARA",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-1.jpeg",
			},
			{
				name: "Hussam Raouf 26",
				badge: "Engineering",
				title: "Corporate Strategy Advisor",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Engineering",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-2.jpeg",
			},
			{
				name: "Joseph Cillian 27",
				badge: "Renewable Energy",
				title: "Land Acquisition Expert",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Renewable Energy",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-3.jpeg",
			},
			{
				name: "Theodore Jovanni 28",
				badge: "Renewable Energy",
				title: "Senior Urban Planner",
				company: "Dan Company",
				yearsOfExperience: "15+ years",
				sector: "Mobility",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-4.jpeg",
			},
			{
				name: "Michael Johnson 29",
				badge: "Renewable Energy",
				title: "Real Estate Development Manager",
				company: "Diriyah Company",
				yearsOfExperience: "20+ years",
				sector: "Environment & Sustainability",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-5.jpeg",
			},
			{
				name: "Samantha Lee 30",
				badge: "Sustainable Agriculture",
				title: "Property Asset Manager",
				company: "ARDARA",
				yearsOfExperience: "15+ years",
				sector: "Smart City & Proptech",
				profileImage: "https://pif-realestate-1.s3.us-east-1.amazonaws.com/experts/expert-6.jpeg",
			},
		];

		const insertedData = await Expert.insertMany(mockData);
		return NextResponse.json({ message: "Mock data added successfully", data: insertedData });
	} catch (error) {
		console.error("Error adding mock data:", error);
		return NextResponse.json({ error: "Error adding mock data" }, { status: 500 });
	}
}
